name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
jobs:
  frontend-build-and-test:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'           

    - name: Install dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint

    - name: Run Tests
      run: npm test

    - name: Build Frontend
      run: npm run build
